\set ON_ERROR_STOP on

CREATE SCHEMA tenant_a;
CREATE SCHEMA tenant_b;
CREATE SCHEMA analytics;

COMMENT ON SCHEMA public IS 'Default schema used as a control for code-viewer.';
COMMENT ON SCHEMA tenant_a IS 'Tenant A schema for PostgreSQL schema-switching checks.';
COMMENT ON SCHEMA tenant_b IS 'Tenant B schema for PostgreSQL schema-switching checks.';
COMMENT ON SCHEMA analytics IS 'Shared analytics schema for PostgreSQL schema-switching checks.';

CREATE TABLE public.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  role text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_a.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('active', 'invited', 'disabled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_a.orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES tenant_a.users(id),
  order_no text NOT NULL UNIQUE,
  total_cents integer NOT NULL CHECK (total_cents >= 0),
  ordered_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_b.users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  status text NOT NULL CHECK (status IN ('active', 'invited', 'disabled')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE tenant_b.orders (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES tenant_b.users(id),
  order_no text NOT NULL UNIQUE,
  total_cents integer NOT NULL CHECK (total_cents >= 0),
  ordered_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE analytics.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_schema text NOT NULL,
  event_name text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX tenant_a_orders_user_id_idx ON tenant_a.orders(user_id);
CREATE INDEX tenant_b_orders_user_id_idx ON tenant_b.orders(user_id);
CREATE INDEX analytics_events_source_schema_idx ON analytics.events(source_schema);

CREATE VIEW tenant_a.active_users AS
SELECT id, name, email, created_at
FROM tenant_a.users
WHERE status = 'active';

CREATE VIEW tenant_b.active_users AS
SELECT id, name, email, created_at
FROM tenant_b.users
WHERE status = 'active';

INSERT INTO public.users (id, name, email, role, created_at) VALUES
  (1, 'Public Admin', 'admin@public.example.test', 'admin', '2026-01-01T00:00:00Z'),
  (2, 'Public Viewer', 'viewer@public.example.test', 'viewer', '2026-01-02T00:00:00Z');

INSERT INTO tenant_a.users (id, name, email, status, created_at) VALUES
  (1, 'Tenant A Alice', 'alice@tenant-a.example.test', 'active', '2026-02-01T00:00:00Z'),
  (2, 'Tenant A Bob', 'bob@tenant-a.example.test', 'invited', '2026-02-02T00:00:00Z'),
  (3, 'Tenant A Carol', 'carol@tenant-a.example.test', 'disabled', '2026-02-03T00:00:00Z');

INSERT INTO tenant_a.orders (id, user_id, order_no, total_cents, ordered_at) VALUES
  (1, 1, 'A-1001', 129900, '2026-02-10T10:00:00Z'),
  (2, 1, 'A-1002', 4590, '2026-02-11T10:00:00Z');

INSERT INTO tenant_b.users (id, name, email, status, created_at) VALUES
  (1, 'Tenant B Alice', 'alice@tenant-b.example.test', 'active', '2026-03-01T00:00:00Z'),
  (2, 'Tenant B Daniel', 'daniel@tenant-b.example.test', 'active', '2026-03-02T00:00:00Z');

INSERT INTO tenant_b.orders (id, user_id, order_no, total_cents, ordered_at) VALUES
  (1, 1, 'B-2001', 8800, '2026-03-10T10:00:00Z'),
  (2, 2, 'B-2002', 34000, '2026-03-11T10:00:00Z');

INSERT INTO analytics.events (id, source_schema, event_name, payload, occurred_at) VALUES
  (1, 'tenant_a', 'user.created', '{"user_id": 1, "plan": "pro"}', '2026-04-01T00:00:00Z'),
  (2, 'tenant_a', 'order.created', '{"order_no": "A-1001"}', '2026-04-01T01:00:00Z'),
  (3, 'tenant_b', 'user.created', '{"user_id": 1, "plan": "team"}', '2026-04-02T00:00:00Z'),
  (4, 'tenant_b', 'order.created', '{"order_no": "B-2001"}', '2026-04-02T01:00:00Z');
